---
driver:
  name: vagrant

transport:
  name: rsync

provisioner:
  name: ansible_playbook
  playbook: default.yml
  roles_path: ../ansible-test-framework/ # replace with the name of your role
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_ruby_for_busser: true
  ansible_verbose: true
  ansible_version: latest
  ansible_diff: true

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: fedora-23
- name: centos-6.7
- name: centos-7.2
- name: debian-7.9
- name: debian-8.2

verifier:
  ruby_bindir: '/usr/bin'

suites:
- name: default
